x = int(input("Enter First Number: "))
y = int(input("Enter Second Number: "))
print("Sum:", x + y)
print("Difference:", x - y)
print("Product:", x * y)
print("Quotient:", x / y)
print("Remainder:", x % y)
print("Exponent:", x ** y)
print("Floor Divided:", x // y)